# Generated by Django 6.0.7 on 2026-07-20 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='encerrada',
            field=models.BooleanField(default=False, verbose_name='Encerrada'),
        ),
    ]
