# Generated by Django 6.0.7 on 2026-07-22 17:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_releases_solicitacoes'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DeadlineHistory',
        ),
    ]
