# Generated by Django 6.0.7 on 2026-07-23 12:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_task_origem_comercial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notificacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('comentario', 'Comentário'), ('atribuicao', 'Atribuição')], max_length=20)),
                ('mensagem', models.CharField(max_length=500)),
                ('lida', models.BooleanField(default=False)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('ator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notificacoes_geradas', to=settings.AUTH_USER_MODEL)),
                ('destinatario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notificacoes', to=settings.AUTH_USER_MODEL)),
                ('tarefa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notificacoes', to='app.task')),
            ],
            options={
                'ordering': ['-criado_em'],
                'indexes': [models.Index(fields=['destinatario', 'lida', '-criado_em'], name='app_notific_destina_371083_idx')],
            },
        ),
    ]
