# Generated by Django 6.0.7 on 2026-07-22 20:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_delete_deadlinehistory'),
        ('app', '0013_task_origem_comercial'),
    ]

    operations = [
    ]
