# Generated by Django 6.0.7 on 2026-07-23 13:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_notificacao'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Comunicacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categoria', models.CharField(choices=[('aviso', 'Aviso'), ('release', 'Release'), ('sistema', 'Sistema')], default='aviso', max_length=20)),
                ('titulo', models.CharField(max_length=200)),
                ('conteudo', models.TextField()),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('autor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='comunicacoes_publicadas', to=settings.AUTH_USER_MODEL)),
                ('release', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='comunicacao', to='app.release')),
            ],
            options={
                'ordering': ['-criado_em'],
            },
        ),
        migrations.CreateModel(
            name='ComunicacaoDestinatario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lida', models.BooleanField(default=False)),
                ('lida_em', models.DateTimeField(blank=True, null=True)),
                ('comunicacao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entregas', to='app.comunicacao')),
                ('destinatario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entregas_comunicacao', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-comunicacao__criado_em'],
            },
        ),
        migrations.AddField(
            model_name='comunicacao',
            name='destinatarios',
            field=models.ManyToManyField(related_name='comunicacoes_recebidas', through='app.ComunicacaoDestinatario', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='comunicacaodestinatario',
            index=models.Index(fields=['destinatario', 'lida'], name='app_comunic_destina_a2d37d_idx'),
        ),
        migrations.AddConstraint(
            model_name='comunicacaodestinatario',
            constraint=models.UniqueConstraint(fields=('comunicacao', 'destinatario'), name='comunicacao_destinatario_unico'),
        ),
    ]
