# Generated by Django 6.0.7 on 2026-07-23 15:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_merge_20260722_2001'),
        ('app', '0015_comunicacao_comunicacaodestinatario_and_more'),
    ]

    operations = [
    ]
