# Generated by Django 6.0.7 on 2026-07-30 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0022_alter_task_fase_pendencias_plantao'),
    ]

    operations = [
        migrations.AddField(
            model_name='erroconhecido',
            name='corrigido',
            field=models.BooleanField(default=False, verbose_name='Corrigido?'),
        ),
        migrations.AddField(
            model_name='erroconhecido',
            name='medida_corretiva',
            field=models.TextField(blank=True, verbose_name='Medida Corretiva'),
        ),
    ]
