# Generated by Django 6.0.7 on 2026-08-03 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0023_erroconhecido_corrigido_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='modulo',
            field=models.CharField(blank=True, choices=[('', 'Sem Módulo Definido'), ('pdv', 'PDV'), ('pdv_pos', 'PDV/POS'), ('portal', 'Portal'), ('tablet_mesa', 'Tablet Mesa'), ('totem', 'Totem'), ('ecommerce', 'E-commerce'), ('nfce', 'NFCe'), ('outros', 'Outros')], default='', max_length=30, verbose_name='Módulo'),
        ),
    ]
