# Generated by Django 6.0.7 on 2026-08-05 13:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0025_procedimentointerno_anexoprocedimento'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AnexoErroConhecido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('arquivo', models.FileField(upload_to='erros-conhecidos/anexos/%Y/%m/')),
                ('nome_original', models.CharField(max_length=255)),
                ('tamanho', models.PositiveBigIntegerField(default=0)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('enviado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='anexos_erros_conhecidos_enviados', to=settings.AUTH_USER_MODEL)),
                ('erro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='anexos', to='app.erroconhecido')),
            ],
            options={
                'ordering': ['-criado_em'],
            },
        ),
    ]
