# Generated by Django 6.0.7 on 2026-08-07 14:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0026_anexoerroconhecido'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SugestaoDesenvolvimento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200, verbose_name='Título')),
                ('modulo', models.CharField(choices=[('pdv', 'PDV'), ('pdv_pos', 'PDV/POS'), ('portal', 'Portal'), ('tablet_mesa', 'Tablet Mesa'), ('totem', 'Totem'), ('ecommerce', 'E-commerce'), ('nfce', 'NFCe'), ('outros', 'Outros')], max_length=30, verbose_name='Módulo')),
                ('descricao', models.TextField(verbose_name='Descrição completa')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('cliente', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sugestoes_desenvolvimento', to='app.cliente')),
                ('criado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sugestoes_desenvolvimento_criadas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-atualizado_em'],
            },
        ),
        migrations.CreateModel(
            name='AnexoSugestaoDesenvolvimento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('arquivo', models.FileField(upload_to='sugestoes-desenvolvimento/anexos/%Y/%m/')),
                ('nome_original', models.CharField(max_length=255)),
                ('tamanho', models.PositiveBigIntegerField(default=0)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('enviado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='anexos_sugestoes_desenvolvimento_enviados', to=settings.AUTH_USER_MODEL)),
                ('sugestao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='anexos', to='app.sugestaodesenvolvimento')),
            ],
            options={
                'ordering': ['-criado_em'],
            },
        ),
    ]
